apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: my-python-app-pipeline
serialPipeline:
  stages:
  - targetId: staging-cluster
    profiles: [staging]
  - targetId: prod-cluster
    profiles: [prod]
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: staging-cluster
gke:
  cluster: projects/project-4b96061c-a0d1-4f8c-ac8/locations/us-central1-a/clusters/cluster-1
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: prod-cluster
requireApproval: true # <--- 🛑 THE MANUAL APPROVAL GATE!
gke:
  # You can use the exact same cluster string here for your PoC! Kustomize handles the naming.
  cluster: projects/project-4b96061c-a0d1-4f8c-ac8/locations/us-central1-a/clusters/cluster-1
