apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-python-app
  labels:
    app: my-python-app
spec:
  replicas: 2 # Runs two copies of your app for high availability
  selector:
    matchLabels:
      app: my-python-app
  template:
    metadata:
      labels:
        app: my-python-app  # name of file...
    spec:
      containers:
      - name: python-app-container
        # This will be automatically replaced with your signed image digest!
        image: us-central1-docker.pkg.dev/project-4b96061c-a0d1-4f8c-ac8/my-docker-repo/app-image@sha256:b7299827e034cd3868d02386d250de0b33381e955b86b80ec91dee61dac111b8
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080 # Change this to the port your Python app listens on (e.g., 5000 for Flask, 8000 for FastAPI)
        resources:
          requests:
            cpu: "150m"
            memory: "256Mi"
          limits:
            cpu: "300m"
            memory: "512Mi"
