apiVersion: skaffold/v4beta7
kind: Config
profiles:
  - name: staging
    manifests:
      kustomize:
        paths: ["overlays/staging"]
  - name: prod
    manifests:
      kustomize:
        paths: ["overlays/prod"]