apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - ../../base
namespace: prod
namePrefix: prod- # This makes your app "prod-my-python-app"

images:
  - name: my-app-image
    newName: us-central1-docker.pkg.dev/project-4b96061c-a0d1-4f8c-ac8/my-docker-repo/app-image
    digest: sha256:719d52851ebfd219fe3830dd3c88b8c87c91005a0f0678716650255314637a0b

replicas:
  - name: my-python-app
    count: 3 # Production gets 3 pods!
patches:
  - target:
      kind: Service
      name: my-python-app-service
    patch: |-
      - op: replace
        path: /spec/ports/0/nodePort
        value: 30081
