apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - ../../base
namespace: prod
namePrefix: prod- # This makes your app "prod-my-python-app"

images:
  - name: my-app-image
    newName: us-central1-docker.pkg.dev/project-4b96061c-a0d1-4f8c-ac8/my-docker-repo/app-image
    digest: sha256:c8aa994511d117bd677cdb838fb69b1afeb3adcb67d506a69cd944008d35b991

replicas:
  - name: my-python-app
    count: 3 # Production gets 3 pods!
patches:
  - target:
      kind: Service
      name: my-python-app-service
    patch: |-
      - op: replace
        path: /spec/ports/0/nodePort
        value: 30081
