apiVersion: v1
kind: Service
metadata:
  name: my-python-app-service # This MUST match the name in base!
spec:
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30081 # <--- Production gets this new port!