apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml

# Repo 1 should update this digest with the exact image digest.
images:
  - name: my-app-image
    newName: us-central1-docker.pkg.dev/project-4b96061c-a0d1-4f8c-ac8/my-docker-repo/app-image
    digest: sha256:6e78db662c4beebb1a02360971547be45e800a21f78d63da76872ad194471ec9
