apiVersion: v1
kind: Service
metadata:
  name: my-python-app-service
  labels:
    app: my-python-app
spec:
  type: NodePort 
  selector:
    app: my-python-app
  ports:
  - protocol: TCP
    port: 80        # The port other services inside the cluster use to talk to this app
    targetPort: 8080 # The actual port your Python app listens on inside the container
    nodePort: 30080 # 
